import { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import AppQueryClient from "./query-client";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Procurement System",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistMono.className} ${geistSans.className} bg-background text-foreground`}
      >
        <AppQueryClient>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </AppQueryClient>
      </body>
    </html>
  );
}
